### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by Silversunset01** [deciobenicio/kb-themeplus-stgray#7]
I've copied this out to the plugins folder and it refuses to register. I can get it working fine with all other plugins but this one just wont pick up. Help?

**Comment by TomNedry** [comment]
Steps for a working install are:

1. Download from https://github.com/deciobenicio/kb-themeplus-stgray/archive/master.zip
2. One will get a file "kb-themeplus-stgray-master.zip"
3. Unzip creates a directory "kb-themeplus-stgray-master"
4. Rename to "Themeplus"
5. Copy to "plugins" folder

**Remark**
The directory name "Themeplus" is required because of:

`// Check if config.php is exist
// If not, get the default-Values
if (file_exists('plugins/Themeplus/config.php')) {
    require_once('plugins/Themeplus/config.php');
} else {
    $themePlusConfig['theme'] = 'default';
}`

as you can see in the file "Plugin.php" in the "Themeplus" directory.

**Comment by deciobenicio** [comment]
Thanks for the help @TomNedry 

@Silversunset01, please follow @TomNedry instructions.
